language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - APPLICATION_ENV="testing" DB="mysql" DB_USERNAME="root"

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p tmp/logs
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
